### ISSUE TITLE
some upgrades for the Board

### ISSUE THREAD

**Issue by MaBe15** [klein0r/pcb-ws2812-wifi-controller#1]
Hi @klein0r,
erstmal danke für die super Arbeit mit der Platine, ich werde mir ein paar fertigen lassen.
Mir sind einge Kleinigkeiten aufgefallen, die ich für meine eigene Bestellung geändert habe, vlt. möchtest du die ja auch ändern:

- Leiterbahnbreite für das Supply-Netz und 5V-Netz vergrößert. Die 0,5mm sind zu gering um die 5A führen zu können bis die Sicherung fällt. [IPC2221](https://www.multi-circuit-boards.eu/leiterplatten-design-hilfe/oberflaeche/leiterbahn-strombelastbarkeit.html)
- Stützkondensatoren für den ESP wie im Datenbaltt beschrieben
- Glättungskondensatoren des Linearreglers an die Werte im Datenblatt angepasst
[pcb-ws2812-wifi-controller-upgrade-main.zip](https://github.com/klein0r/pcb-ws2812-wifi-controller/files/6680438/pcb-ws2812-wifi-controller-upgrade-main.zip)

Ansonsten ist das eine super Platine, danke dafür.
Gruß
Marcus

**Comment by MaikPerezHeide** [comment]
Hallo Marcus, ist  es möglich, in Deinem Entwurf, den ESP 12F einfach 1:1 gegen einen ESP32-WROOM32D auszutauschen, oder muss da ggf. noch etwas an der Verkabelung geändert werden? Ich bin neu in diesem Bereich, habe auch wenig Ahnung von Elektronik. Ich würde aber gerne den ESP32 für dieses Projekt verwenden. Vielen Dank im Voraus.
Gruß
Maik

**Comment by MaBe15** [comment]
Hallo Maik,
wenn ich es auf die schnelle richtig gesehen habe, dann stimmen die mechanischen Abmessungen des ESP32-WROOM32D mit denen des ESP12F nicht überein. Auch die Anzahl PINs und die Pinbelegung ist nicht identisch. Ein 1:1 Austausch ist also nicht möglich. Du müsstest also den Schaltplan und das Routing auf dem PCB komplett überarbeiten.

Gruß
Marcus

**Comment by Philip52** [comment]
@MaBe15 
Hi. Danke für dein Update. Ich wollte es gerade bei jlcpcb in Auftrag geben aber die können die Datei nicht öffnen. Hattest du das Problem auch oder hab ich evtl n Fehler gemacht. Grüße 
Philip

**Comment by nocodeman55** [comment]
> Hallo Marcus, ist es möglich, in Deinem Entwurf, den ESP 12F einfach 1:1 gegen einen ESP32-WROOM32D auszutauschen, oder muss da ggf. noch etwas an der Verkabelung geändert werden? Ich bin neu in diesem Bereich, habe auch wenig Ahnung von Elektronik. Ich würde aber gerne den ESP32 für dieses Projekt verwenden. Vielen Dank im Voraus.
> Gruß
> Maik
![back32](https://user-images.githubusercontent.com/79729477/154364202-948515d7-c5ea-4fd4-8f0f-9cc5ab78c101.jpg)

![front32](https://user-images.githubusercontent.com/79729477/154364191-c76f1bc5-cc03-4d7b-bfb3-ab85630a6fb0.jpg)

Sorry i need to reply in English 

I found this module ESP-C3-12F Module

This might work - it have the same size and is ESP32 - should drop in - but im not sure about the needed pins?
