### ISSUE TITLE
Assembly ? 

### ISSUE THREAD

**Issue by bangboomben** [klein0r/pcb-ws2812-wifi-controller#5]
Hi,

newbie-question: do the boards come pre-assembled with all the parts ?
If not, do I require any extra file for JLCPCB ?

Cheers
Ben

**Comment by klein0r** [comment]
I always order the plain PCB without parts and solder them on my own.

There is also a service where you can order pre-assembled PCB. But: I haven't provided a file in this repository which component belongs to which location in which orientation...
